package constants

const (
	TableAddress                = "t_address"
	TableAddressHistory         = "t_address_history"
	TableBuilding               = "t_building"
	TableBuildingHistory        = "t_building_history"
	TableRoom                   = "t_room"
	TableRoomHistory            = "t_room_history"
	TableFloor                  = "t_floor"
	TableFloorHistory           = "t_floor_history"
	TablePeople                 = "t_people"
	TablePeopleHistory          = "t_people_history"
	TableLabel                  = "t_label"
	TableLabelHistory           = "t_label_history"
	TableShop                   = "t_shop"
	TableShopHistory            = "t_shop_history"
	TableEnterprise             = "t_enterprise"
	TableEnterpriseHistory      = "t_enterprise_history"
	TableOrganization           = "t_organization"
	TableOrganizationHistory    = "t_organization_history"
	TableVisitRecord            = "t_visit_record"
	TableAddr2Label             = "r_addr2label"
	TableBd2Addr                = "r_bd2addr"
	TableBd2Label               = "r_bd2label"
	TableEnt2FloorEnroll        = "r_ent2floor_enroll"
	TableEnt2FloorEnrollHistory = "r_ent2floor_enroll_history"
	TableEnt2FloorOffice        = "r_ent2floor_office"
	TableEnt2FloorOfficeHistory = "r_ent2floor_office_history"
	TableEnt2Label              = "r_ent2label"
	TableEnt2LabelHistory       = "r_ent2label_history"
	TableOrg2Addr               = "r_org2addr"
	TableOrg2AddrHistory        = "r_org2addr_history"
	TableOrg2Bd                 = "r_org2bd"
	TableOrg2BdHistory          = "r_org2bd_history"
	TableOrg2Label              = "r_org2label"
	TableContact2Pep            = "r_contact2pep"
	TableContact2PepHistory     = "r_contact2pep_history"
	TablePep2EntJob             = "r_pep2ent_job"
	TablePep2EntJobHistory      = "r_pep2ent_job_history"
	TablePep2Label              = "r_pep2label"
	TablePep2LabelHistory       = "r_pep2label_history"
	TablePep2Org                = "r_pep2org"
	TablePep2OrgHistory         = "r_pep2org_history"
	TablePep2Pep                = "r_pep2pep"
	TablePep2PepHistory         = "r_pep2pep_history"
	TablePep2RoomHuJi           = "r_pep2room_huji"
	TablePep2RoomHuJiHistory    = "r_pep2room_huji_history"
	TablePep2RoomHuJiHis        = "r_pep2room_huji_his"
	TablePep2RoomLive           = "r_pep2room_live"
	TablePep2RoomLiveHistory    = "r_pep2room_live_history"
	TablePep2RoomLiveHis        = "r_pep2room_live_his"
	TablePep2Shop               = "r_pep2shop"
	TablePep2ShopHistory        = "r_pep2shop_history"
	TableRoom2Label             = "r_room2label"
	TableRoom2LabelHistory      = "r_room2label_history"
	TableShop2Bd                = "r_shop2bd"
	TableShop2BdHistory         = "r_shop2bd_history"
	TableShop2Label             = "r_shop2label"
	TableShop2LabelHistory      = "r_shop2label_history"

	TableSearchAddress    = "t_search_address"
	TableSearchBuilding   = "t_search_building"
	TableSearchRoom       = "t_search_room"
	TableSearchPeople     = "t_search_people"
	TableSearchShop       = "t_search_shop"
	TableSearchEnterprise = "t_search_enterprise"

	TableWideAddress      = "t_wide_address"
	TableWideBuilding     = "t_wide_building"
	TableWideRoom         = "t_wide_room"
	TableWidePeople       = "t_wide_people"
	TableWideShop         = "t_wide_shop"
	TableWideEnterprise   = "t_wide_enterprise"
	TableWideOrganization = "t_wide_organization"
	TableWidePep2Label    = "t_wide_pep2label"
	TableWidePep2RoomLive = "t_wide_pep2room_live"
	TableWidePep2RoomHuJi = "t_wide_pep2room_huji"
	TableWideOperateLog   = "t_wide_operate_log"

	TablePeopleStats = "t_people_stats"
	TableRoomStats   = "t_room_stats"

	TableTaskEvent         = "t_task_event"
	TableTaskEventOperator = "t_task_event_operator"
)
